services:
  wiremock:
    image: holomekc/wiremock-gui:3.6.9
    container_name: my_wiremock
    ports:
      # This is just an example of a port mapping
      - "8089:8089"
      - "8088:8088"
    environment:
      WIREMOCK_OPTIONS: >
        --port=8089
        --https-port=8088
        --max-request-journal=1000
        --local-response-templating
        --root-dir=/home/wiremock/storage
